name: Deploy - Azure Government

on:
  push:
    branches: [main]
    paths:
      - "modules/**"
      - "environments/gov/**"
      - "backend-config/gov.backend.hcl"
      - "main.tf"
      - "variables.tf"
      - "providers.tf"
      - "outputs.tf"

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      cloud: gov
      environment_name: gov-prod
    secrets: inherit
